In [25]:
import numpy as np

In [26]:
np.__version__

'1.26.4'

Converting python list into numpy array

In [27]:
list1 = [1,2,3,4]


In [28]:
import numpy as np

In [29]:
np.array(list1)

array([1, 2, 3, 4])

In [30]:
matrix = [ [1,3] , [2,4] ] 
np.array(matrix)

array([[1, 3],
       [2, 4]])

Creating numpy array from range function  


np.arange(start,end,step_size)


In [31]:
arr = np.arange(0,10,2)
print(arr)

[0 2 4 6 8]


In [32]:
arr

array([0, 2, 4, 6, 8])

In [33]:
arr = np.arange(0,10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


Creating array of zeros and ones

In [34]:
arr  = np.zeros(5)
print(arr)

[0. 0. 0. 0. 0.]


In [35]:
arr = np.zeros((5,5))
print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [36]:
arr = np.ones(5)
print(arr)

[1. 1. 1. 1. 1.]


In [37]:
arr = np.ones((5,5))
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


creating array with evenly spacing among the elements

np.linspace(start,end,total_ele)

In [38]:
arr = np.linspace(0,10,5)
print(arr)

[ 0.   2.5  5.   7.5 10. ]


In [39]:
arr = np.linspace(0,10,3)
print(arr)

[ 0.  5. 10.]


Identity Matrix


In [40]:
arr = np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Random Functions

Difference between rand and randn ?

**rand <- uniform distribution [0,1)
**randn <- std normal distribution (mean=0 , var=1)

In [41]:
arr = np.random.rand(5)
print(arr)

[0.33002653 0.34232829 0.803262   0.22788199 0.8206624 ]


In [42]:
arr = np.random.randn(5)
print(arr)

[-0.01843206 -0.96397478  1.29147827  1.09477376  1.19721595]


In [43]:
arr = np.random.rand(3,3)
print(arr)

[[0.85184977 0.16232743 0.02637372]
 [0.98717365 0.19095748 0.15034773]
 [0.63272102 0.85930497 0.9551549 ]]


In [44]:
arr = np.random.randint(0,100,10)
print(arr)

[38 80  9 63 17 65  1 99  4 79]


In [45]:
arr.sum()

455

In [46]:
arr.max()

99

In [47]:
arr.min()

1

In [48]:
arr.argmax()
#gives the index of max ele

7

In [49]:
arr.argmin()
#gives the index of min ele

6

In [36]:
arr = np.random.randint(0,100,(3,5))
print(arr)

[[58 70 16 64 85]
 [51 43 10 10 98]
 [80 51 27 68  6]]


# Indexing and slicing       


#### Broadcasting  

It works like call by referece

In [50]:
l1 = np.arange(0,11)
print(l1)
l2 = l1[3:]
l2[0:] = 1
print(l1)

[ 0  1  2  3  4  5  6  7  8  9 10]
[0 1 2 1 1 1 1 1 1 1 1]


In [51]:
l1 = np.arange(0,11)
print(l1)
l1[3:] = 5
print(l1)

[ 0  1  2  3  4  5  6  7  8  9 10]
[0 1 2 5 5 5 5 5 5 5 5]


#### Conditional selection 

Its a way to apply condition on array and then filter the array elements according to the condition

In [54]:
arr = np.arange(0,20)
bool_arr = arr > 10
print(bool_arr)
print(arr[bool_arr])

[False False False False False False False False False False False  True
  True  True  True  True  True  True  True  True]
[11 12 13 14 15 16 17 18 19]


In [2]:
import numpy as np
a1 = [1,3,'4']
print(np.array(a1))

['1' '3' '4']


In [5]:
print(type(a1[1]))

<class 'int'>


In [6]:
a1 = np.arange(0,4)
print(a1)

[0 1 2 3]


In [37]:
a2 = a1.reshape(2,2)
a3 = a2
print(a2)
print(a3)

a3.sum(axis=1)

[[0 1]
 [2 3]]
[[0 1]
 [2 3]]


array([1, 5])

In [22]:
a2.sum(axis=1)

array([1, 5])

In [48]:
a1 = [[1,2,3,4] , [5,6,7,8]]
a1 = np.array(a1)
b1 = np.arange(0,8)
b1 = b1.reshape(2,4)
print(a1)
print()
print(b1)

[[1 2 3 4]
 [5 6 7 8]]

[[0 1 2 3]
 [4 5 6 7]]


In [61]:
print(np.concatenate([a1,b1],axis=1))
print()
print(np.hstack([a1,b1]))

[[1 2 3 4 0 1 2 3]
 [5 6 7 8 4 5 6 7]]

[[1 2 3 4 0 1 2 3]
 [5 6 7 8 4 5 6 7]]


#### Splitting array into multiple array


In [74]:
l1 = np.arange(0,10)
l2 = np.array_split(l1,5)
print(l2[4])

[8 9]


## Reshape N-d TO 1-D matrix

In [11]:

import numpy as np
ar = np.arange(0,10).reshape(2,5)
print(ar.ndim)
print(ar)
print()

ar  = ar.reshape(-1)
print(ar.ndim)
print(ar)


2
[[0 1 2 3 4]
 [5 6 7 8 9]]

1
[0 1 2 3 4 5 6 7 8 9]


In [12]:
import numpy as np
ar = np.arange(0,5)
type(ar[0])

numpy.int32

In [8]:
%timeit [j**4 for j in range(1,9)]

880 ns ± 59.9 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [9]:
%timeit np.arange(1,10)**4

2.51 µs ± 381 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [31]:
ar = np.zeros(5)
for i in ar:
    print(int(i))


0
0
0
0
0


In [47]:
ar = np.linspace(0,10,6) 
ar

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [53]:
ar = np.random.rand(5)
ar


array([0.59900612, 0.72994721, 0.34944934, 0.68019876, 0.7494816 ])

In [55]:
ar = np.random.randint(0,3,10)
ar

array([0, 0, 1, 2, 2, 1, 0, 2, 1, 0])

In [1]:
a = '1'
print(type(a))

<class 'str'>


In [3]:
import numpy as np
arr = np.arange(0,10)
print(arr.ndim)
print(arr)
print(arr.shape)

1
[0 1 2 3 4 5 6 7 8 9]
(10,)


In [17]:
arr = np.array([[1,2],[3,4]])
print(arr)
print(arr.ndim)
Shape = arr.shape
print(Shape)
print()
ar = np.arange(0,15).reshape(1,3,5)
print(ar)
print(ar.shape)
print(ar.ndim)
ar = ar.reshape(-1)
print()
print(ar.ndim)
print(ar)
print(type(ar.ndim))

[[1 2]
 [3 4]]
2
(2, 2)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]]
(1, 3, 5)
3

1
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
<class 'int'>


# Numpy Arithmetic Operation

### 1D

In [24]:
import numpy as np
arr = np.array([1,2,3,4])
print(arr)

# arr + 3  ==  np.add(arr,3)   both ways are valid

print(arr+3)  # 3 gets added to each value

[1 2 3 4]
[4 5 6 7]


In [31]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([1,2,3,4,5])
print(arr1+arr2)  # To add 2 array shape of both array must be same


[ 2  4  6  8 10]


In [28]:
# Similarly other operation are also supported 
# arr + 3  == np.add(arr,3)
# arr - 3  == np.subtract(arr,3)
# arr * 3  == np.multiply(arr,3)
# arr / 3  == np.divide(arr,3)
# arr % 3  == np.mod(arr,3)
# arr **3  == np.power(arr,3)
# 1/arr    == np.reciprocal(arr)

In [51]:
# Special Case : Divide by zero
# Numpy doesnot throw error because divide by zero is represented by inf in Numpy
# Numpy does provide warning though
ar = np.array([1,2,0])
print(1/ar)

[1.  0.5 inf]


C:\Users\katus\AppData\Local\Temp\ipykernel_11720\671915843.py:5: RuntimeWarning: divide by zero encountered in divide
  print(1/ar)


In [71]:
ar = np.array([4,3,1,6,7,10])
print("min: ",np.min(ar)) # return the minimum element
print("pos: ",np.argmin(ar)) # return the index of minimum element

print()
# There is anather way to write the same thing
print("min: ",ar.min())
print("pos: ",ar.argmin())

# max and its index
print()
print("max: ",ar.max())
print("Pos: ",ar.argmax())

# square root
print("sqaure root: ",np.sqrt(ar))

# Sin and cos  
# Note : All angles are considered in radian 
arr = np.array([0,0.785398,90])
print("sin: ",np.sin(arr))
print("cos: ",np.cos(arr))


#commultive sum // prefix sum 
arr = np.array([1,2,3,4,5])
print()
print("prefix sum: ",arr.cumsum())

min:  1
pos:  2

min:  1
pos:  2

max:  10
Pos:  5
sqaure root:  [2.         1.73205081 1.         2.44948974 2.64575131 3.16227766]
sin:  [0.         0.70710667 0.89399666]
cos:  [ 1.          0.7071069  -0.44807362]

prefix sum:  [ 1  3  6 10 15]


### 2D

In [36]:
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr)
print()

print(arr + 10)   # 10 gets added to every number

[[1 2 3 4]
 [5 6 7 8]]

[[11 12 13 14]
 [15 16 17 18]]


In [49]:
arr1 = np.array([[1,2,3],[3,4,5],[8,9,10]])
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr1)
print()
print(arr2)
print()

print(arr1*arr2)  # Operation will be performed ele by ele 

# To perform operation on N-D array
# 1) Either shape of both array should be same eg( (3,3) and (3,3) )
# 2) Or Last part(till min both shape) of shape should be same
#    e.g    (3,4) == (4,)
#           (3,4) != (2,4)
#           (1,3,4) == (4,)    
#           (1,3,4) == (3,4)


[[ 1  2  3]
 [ 3  4  5]
 [ 8  9 10]]

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[ 1  4  9]
 [12 20 30]
 [56 72 90]]


In [102]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

print(arr.max(axis=0))
print(arr.argmax(axis=0))
print()
print(arr.cumsum(axis=0))
print(arr.cumsum(axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[7 8 9]
[2 2 2]

[[ 1  2  3]
 [ 5  7  9]
 [12 15 18]]
[[ 1  3  6]
 [ 4  9 15]
 [ 7 15 24]]


In [99]:
ar = np.array([[[2,3],[4,5]],[[6,7],[8,9]]])
print("Given 3D matrix")
print(ar)
print()
print("**********************")
print()
print(ar.sum(axis=0))
print()
print(ar.sum(axis=1))
print()
print(ar.sum(axis=2))

Given 3D matrix
[[[2 3]
  [4 5]]

 [[6 7]
  [8 9]]]

**********************

[[ 8 10]
 [12 14]]

[[ 6  8]
 [14 16]]

[[ 5  9]
 [13 17]]


# Broadcasting

In [103]:
# When we try to perform the arithmetic operation then shape of array should be same . 
# In case of not both array should be able to broadcasted successfully

In [106]:
# Lets consider we want to perform the arith operation on 2 array of shape (a,b,c) and (p,q,r)
# We will be able to perform operation iff ( a==p || a==1 || p==1  ) && ( b==q || b==1 || q==1 ) && ( c==r || c==1 || r==1 )  
# In case of array with (a,b,c) and (q,r) shape : This will also be successfully works if condition on q and r satisfy .  

In [107]:
ar = np.array([1,2,3])
ar2 = np.array([[1],[2],[3]])
print(ar)
print(ar.shape)
print()
print(ar2)
print(ar2.shape)

print()
print(ar + ar2)

[1 2 3]
(3,)

[[1]
 [2]
 [3]]
(3, 1)

[[2 3 4]
 [3 4 5]
 [4 5 6]]


# Indexing

### 1D

In [122]:
import numpy as np
ar = np.array([4,3,2,1,0])
print("First ele: ",ar[0])
print("Last ele: ",ar[ar.size - 1])
print("Last ele: ",ar[-1])
# support negative index as well . Last element index will be -1

First ele:  4
Last ele:  0
Last ele:  0


### 2D

In [127]:
ar = np.array([[1,2,3],[3,4,5],[6,7,8]])
print(ar)

print()
print(ar[0])

print(ar[0,0]) # will give the element
print(ar[0][0]) # above and this is same

[[1 2 3]
 [3 4 5]
 [6 7 8]]

[1 2 3]
1
1


# Slicing 

### 1D

In [130]:
# suppose array is ar
# ar[start : End : step_count ]

In [129]:
import numpy as np
ar = np.array([4,3,2,1,0])
print("First 3 ele ", ar[:3])
print("Last 3 ele: ",ar[2:])

First 3 ele  [4 3 2]
Last 3 ele:  [2 1 0]


In [134]:
ar = np.arange(0,10)
print(ar)
print()
print(ar[::2])
print(ar[3:8:2])

[0 1 2 3 4 5 6 7 8 9]

[0 2 4 6 8]
[3 5 7]


### 2D

In [139]:
ar = np.array([[1,2,3],[3,4,5],[6,7,8]])
print(ar)
# suppose out task is to print [4,5] 
print()
print(ar[1,1:])
print(ar[1][1:]) # This can be done in above both ways

[[1 2 3]
 [3 4 5]
 [6 7 8]]

[4 5]
[4 5]


# Iterating Numpy Array

### 1D

In [150]:
import numpy as np
ar = np.random.randint(0,10,5)
print(ar)
print()
# first way of iterating
for i in ar:
    print(i)

print()
# second way of iterating
for i in range(ar.size):
    print(ar[i])

[8 4 0 7 2]

8
4
0
7
2

8
4
0
7
2


In [158]:
ar = np.random.randint(0,10,5)
print("Original: ",ar)
print("Reversed: ",ar[::-1])

Original:  [4 6 8 6 3]
Reversed:  [3 6 8 6 4]


### 2D

In [190]:
ar = np.array([[1,2,3,4],[5,6,7,8]])
print(ar)
print()

# iterating rows
for i in ar:
    print(i)
print()
# iterating every element
for i in ar:
    for j in i:
        print(j)
print()
# Anather method of iteration using function 
for i in np.nditer(ar):
    print(i)
print()
# Method 3 of iteration
for i in range(ar.shape[0] ): # this will give the total rows
    for j in range(ar.shape[1]):
        print(ar[i][j])

# Iteration which gives both ele and its index
for i,d in np.ndenumerate(ar):
    print(f"index: {i} and Data: {d}")

[[1 2 3 4]
 [5 6 7 8]]

[1 2 3 4]
[5 6 7 8]

1
2
3
4
5
6
7
8

1
2
3
4
5
6
7
8

1
2
3
4
5
6
7
8
index: (0, 0) and Data: 1
index: (0, 1) and Data: 2
index: (0, 2) and Data: 3
index: (0, 3) and Data: 4
index: (1, 0) and Data: 5
index: (1, 1) and Data: 6
index: (1, 2) and Data: 7
index: (1, 3) and Data: 8


In [192]:
ar = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(ar)
print()
print(ar.sum(axis=0))
print(ar.sum(axis=1))
print(ar.sum(axis=2))


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

[[ 6  8]
 [10 12]]
[[ 4  6]
 [12 14]]
[[ 3  7]
 [11 15]]


# Copy Vs View

In [193]:
# Copy function creates new seperate array ( Its like call by value where new variable gets created )
# View function dont create new array ( Its like call by reference ) 
# changes made in copy array won't affect original array whereas changes made in view array will affect

In [194]:
import numpy as np
arr = np.array([1,2,3])
arr_copy = arr.copy()

arr_copy[0] = 10
print(arr)
print(arr_copy)

[1 2 3]
[10  2  3]


In [195]:
import numpy as np
arr = np.array([1,2,3])
arr_view = arr.view()

arr_view[0] = 10
print(arr)
print(arr_view)

[10  2  3]
[10  2  3]


# Join and Split function

In [10]:
import numpy as np
a1 = np.array([1,2,3])   
a2 = np.array([4,5])
a3 = a1.copy()
print(np.concatenate((a1,a2,a3)))


[1 2 3 4 5 1 2 3]


In [19]:
ar1 = np.array([[1,2],[3,4]])
ar2 = np.array([[5,6],[7,8]])
print(ar1)
print()
print(ar2)
print()

print(np.concatenate((ar1,ar2),axis=0)) # Vertical concatenation
print()
print(np.concatenate((ar1,ar2),axis=1)) # Horizontal concatenation


# Above thing can also be done using stack function 
# np.hstack ( Horizontal concatenation )
# np.vstack ( Vertical concatenation )

print()
print(np.hstack((ar1,ar2)))

[[1 2]
 [3 4]]

[[5 6]
 [7 8]]

[[1 2]
 [3 4]
 [5 6]
 [7 8]]

[[1 2 5 6]
 [3 4 7 8]]

[[1 2 5 6]
 [3 4 7 8]]


In [28]:
# np.array_split(Which array to split , kitne mai split karna hai )

a1 = np.array([1,2,3,4,5,6])
arr = np.array_split(a1,3)  # return the list of arrays
print(arr)

print(np.array_split(a1,4))
# If split are more than the size of array then empty array gets created


[array([1, 2]), array([3, 4]), array([5, 6])]
[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [40]:
# splitting 2D array
ar1 = np.array([[1,2],[3,4],[4,5]])
#ar2 = np.array([[5,6],[7,8]])
print(ar1)
print()
print(np.array_split(ar1,3)) # splitting according to the rows i.e axis = 1 
print()
print(np.array_split(ar1,3,axis=1))


[[1 2]
 [3 4]
 [4 5]]

[array([[1, 2]]), array([[3, 4]]), array([[4, 5]])]

[array([[1],
       [3],
       [4]]), array([[2],
       [4],
       [5]]), array([], shape=(3, 0), dtype=int32)]


# Search 

In [120]:
import numpy as np
ar1 = np.array([1,2,3,4,6,5,3,2,1,8])
indexes = np.where(ar1 == 2)
print(indexes)


# Where function returns the list of indexes where element maches

(array([1, 7], dtype=int64),)


# Search Sorted Array

In [11]:
# Used to search in sorted array . It does searching by binary search .
# It return index of element where element can be inserted if all elements needs to stored in sorted order
# List needs to be sorted before using the function.

In [17]:
import numpy as np
ar1 = np.array([12,2,3,4,5,2,1,3]) # 1 2 2 3 3 4 5 12

ar1.sort()
print(np.searchsorted(ar1,5))

# searchsorted( Array , Element ) 


6


# Sort 

In [122]:
import numpy as np
ar1 = np.random.randint(0,10,5)
ar1.sort()
print(ar1)

# Sort function sort the array in increasing order


# sorting in decreasing order
print(np.sort(ar1)[::-1])


[0 0 1 2 6]
[6 2 1 0 0]


In [27]:
# Sorting in 2D

ar1 = np.random.randint(0,20,16).reshape(4,4)
print(ar1)

print()
ar1.sort()  # Elements gets sorted along axis = 1
print(ar1)
print()
ar1.sort(axis=0) # Elements are sorted along axis = 0
print(ar1)

[[18  5 15 10]
 [ 5  8  9  4]
 [ 4  9 18 14]
 [19 17 18 17]]

[[ 5 10 15 18]
 [ 4  5  8  9]
 [ 4  9 14 18]
 [17 17 18 19]]

[[ 4  5  8  9]
 [ 4  9 14 18]
 [ 5 10 15 18]
 [17 17 18 19]]


# Shuffle

In [40]:
import numpy as np
ar1 = np.array([1,1,2,3,4])
np.random.shuffle(ar1)
print(ar1)

# Shuffle function shuffles the array . It does changes in parameter array . So it does not return anything

[2 4 1 1 3]


# Unique 

In [45]:
import numpy as np
ar1 = np.array([1,2,3,2,1,1,3,4,5])
print(np.unique(ar1,return_index=True,return_counts = True))

# Unique return the list of unique elements . Unique also return indexes of those unique elements ( return_index = true )
# Unique function can return the count of elements as well (return_counts = true )

(array([1, 2, 3, 4, 5]), array([0, 1, 2, 7, 8], dtype=int64), array([3, 2, 2, 1, 1], dtype=int64))


# Flatten Vs Ravel Vs Reshape(-1)

In [50]:
# all this 3 functions used to convert Nd to 1D array

In [51]:
# Flatten : Return the copy of array after performing the conversion
# Ravel : Try to return View . If fails returns copy
# reshape(-1) : Same like ravel

In [57]:
ar1 = np.random.randint(0,10,15).reshape(3,5)
print(ar1)

print(ar1.reshape(-1))  # Elements are taken row-wise
x = ar1.reshape(-1)
x[3] = 300
print(x)
ar1        # can easily seen view of ar1 was created by reshape(-1)

[[3 4 7 4 7]
 [2 0 2 9 2]
 [6 3 7 0 0]]
[3 4 7 4 7 2 0 2 9 2 6 3 7 0 0]
[  3   4   7 300   7   2   0   2   9   2   6   3   7   0   0]


array([[  3,   4,   7, 300,   7],
       [  2,   0,   2,   9,   2],
       [  6,   3,   7,   0,   0]])

In [62]:
ar1 = np.random.randint(0,10,15).reshape(3,5)
print(ar1)

# Flatten orders  C:Row-wise F:Column-wize A:
print(ar1.flatten(order='F'))
print(ar1.flatten(order='A'))
print(ar1.flatten(order='K'))

print(ar1.ravel(order='F'))

[[1 5 0 4 0]
 [7 5 6 2 5]
 [2 6 6 0 3]]
[1 7 2 5 5 6 0 6 6 4 2 0 0 5 3]
[1 5 0 4 0 7 5 6 2 5 2 6 6 0 3]
[1 5 0 4 0 7 5 6 2 5 2 6 6 0 3]
[1 7 2 5 5 6 0 6 6 4 2 0 0 5 3]


# Insert 

In [67]:
ar = np.array([1,2,3,4])
x = np.insert(ar,2,200) # return the copy of array after inserting . Original remains unchanged
print(x)
print(ar)
y = np.insert(ar,(2,4),50)
print(y)

# insert( array , Index , Element )

[  1   2 200   3   4]
[1 2 3 4]
[ 1  2 50  3  4 50]


In [75]:
ar = np.array([[1,2,3],[4,5,6]])
print(ar)
print()
print(np.insert(ar,2,[7,8,9],axis=0)) 
print()
print(np.insert(ar,3,[1,2],axis=1))

[[1 2 3]
 [4 5 6]]

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 2 3 1]
 [4 5 6 2]]


# Delete

In [78]:
import numpy as np
ar = np.array([1,2,3,4])
print(np.delete(ar,1))
print(ar)

# Delete ( array , Index )


[1 3 4]
[1 2 3 4]


In [95]:
ar = np.array([[1,2,3],[4,5,6]])
print(ar)
print()
ar1 = np.array([1])
for i in np.nditer(ar):
    ar1 = np.append(ar1,i)
print(ar1)

[[1 2 3]
 [4 5 6]]

[1 1 2 3 4 5 6]


# Matrix 

In [97]:
import numpy as np
m1 = np.matrix([[1,2],[3,4]])
m2 = np.matrix([[5,4],[1,2]])
print(m1)
print(m2)
print()
print(m1*m2) # It does matrix multiplication

[[1 2]
 [3 4]]
[[5 4]
 [1 2]]

[[ 7  8]
 [19 20]]


In [100]:
m1 = np.matrix([1,2,3])
print(m1)
print(m1.shape)
print(m1.ndim)
print(m1 + 3) # Broadcasting can be done

[[1 2 3]]
(1, 3)
2
[[4 5 6]]


## Transpose

In [103]:
m1 = np.matrix([[1,2],[3,4]])
print(m1)

print()
print("transpose of Matrix : ")
print(np.transpose(m1))

[[1 2]
 [3 4]]

transpose of Matrix : 
[[1 3]
 [2 4]]


## Inverse 

In [105]:
m1 = np.matrix([[1,2],[3,4]])
print(m1)
print(np.linalg.inv(m1))

[[1 2]
 [3 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]


## Power of matrix

In [109]:
m1 = np.matrix([[1,2],[3,4]])
print(m1)
print()

print(np.linalg.matrix_power(m1,2)) # gives the m1^2
print(np.linalg.matrix_power(m1,0)) # gives the identity matrix
print(np.linalg.matrix_power(m1,-1)) # gives the inverse

[[1 2]
 [3 4]]

[[ 7 10]
 [15 22]]
[[1 0]
 [0 1]]
[[-2.   1. ]
 [ 1.5 -0.5]]


## Determinant

In [116]:
m1 = np.matrix([[1,2],[3,4]])
print(m1)
print(np.linalg.det(m1))

# m2 = np.matrix([1,2,3])
# print(np.linalg.det(m2)) # Not working coz m2 is not square matrix

[[1 2]
 [3 4]]
-2.0000000000000004


# Mean Var and std 

In [118]:
a1 = np.array([1,2,3,4,5])
print(a1)

print("Mean: ", np.mean(a1))
print("Variance : ",np.var(a1))
print("Std Deviation : ",np.std(a1))

[1 2 3 4 5]
Mean:  3.0
Variance :  2.0
Std Deviation :  1.4142135623730951


In [125]:
ar = np.arange(0,10)
print(ar)
print(np.flip(ar))  

[0 1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1 0]
